// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: pvz/v1/packaging.proto

package pvz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackagingType int32

const (
	PackagingType_UNKNOWN PackagingType = 0
	PackagingType_WRAP    PackagingType = 1
	PackagingType_BAG     PackagingType = 2
	PackagingType_BOX     PackagingType = 3
)

// Enum value maps for PackagingType.
var (
	PackagingType_name = map[int32]string{
		0: "UNKNOWN",
		1: "WRAP",
		2: "BAG",
		3: "BOX",
	}
	PackagingType_value = map[string]int32{
		"UNKNOWN": 0,
		"WRAP":    1,
		"BAG":     2,
		"BOX":     3,
	}
)

func (x PackagingType) Enum() *PackagingType {
	p := new(PackagingType)
	*p = x
	return p
}

func (x PackagingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackagingType) Descriptor() protoreflect.EnumDescriptor {
	return file_pvz_v1_packaging_proto_enumTypes[0].Descriptor()
}

func (PackagingType) Type() protoreflect.EnumType {
	return &file_pvz_v1_packaging_proto_enumTypes[0]
}

func (x PackagingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackagingType.Descriptor instead.
func (PackagingType) EnumDescriptor() ([]byte, []int) {
	return file_pvz_v1_packaging_proto_rawDescGZIP(), []int{0}
}

var File_pvz_v1_packaging_proto protoreflect.FileDescriptor

var file_pvz_v1_packaging_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x76, 0x7a, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x76, 0x7a, 0x2a, 0x38, 0x0a,
	0x0d, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57,
	0x52, 0x41, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x47, 0x10, 0x02, 0x12, 0x07,
	0x0a, 0x03, 0x42, 0x4f, 0x58, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x76, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pvz_v1_packaging_proto_rawDescOnce sync.Once
	file_pvz_v1_packaging_proto_rawDescData = file_pvz_v1_packaging_proto_rawDesc
)

func file_pvz_v1_packaging_proto_rawDescGZIP() []byte {
	file_pvz_v1_packaging_proto_rawDescOnce.Do(func() {
		file_pvz_v1_packaging_proto_rawDescData = protoimpl.X.CompressGZIP(file_pvz_v1_packaging_proto_rawDescData)
	})
	return file_pvz_v1_packaging_proto_rawDescData
}

var file_pvz_v1_packaging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pvz_v1_packaging_proto_goTypes = []any{
	(PackagingType)(0), // 0: pvz.PackagingType
}
var file_pvz_v1_packaging_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pvz_v1_packaging_proto_init() }
func file_pvz_v1_packaging_proto_init() {
	if File_pvz_v1_packaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pvz_v1_packaging_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pvz_v1_packaging_proto_goTypes,
		DependencyIndexes: file_pvz_v1_packaging_proto_depIdxs,
		EnumInfos:         file_pvz_v1_packaging_proto_enumTypes,
	}.Build()
	File_pvz_v1_packaging_proto = out.File
	file_pvz_v1_packaging_proto_rawDesc = nil
	file_pvz_v1_packaging_proto_goTypes = nil
	file_pvz_v1_packaging_proto_depIdxs = nil
}
